//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music mute during 48Vdc operation.
        /// </summary>
        public static string _dcOperationMenuEntry {
            get {
                return ResourceManager.GetString("_dcOperationMenuEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string _languageSelect {
            get {
                return ResourceManager.GetString("_languageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP &amp; Room EQ.
        /// </summary>
        public static string _lspBlockTitle {
            get {
                return ResourceManager.GetString("_lspBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 4x4 zone card.
        /// </summary>
        public static string _mainAddNewCard {
            get {
                return ResourceManager.GetString("_mainAddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1.
        /// </summary>
        public static string _mainAlarm {
            get {
                return ResourceManager.GetString("_mainAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 2.
        /// </summary>
        public static string _mainAlert {
            get {
                return ResourceManager.GetString("_mainAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        public static string _mainAux {
            get {
                return ResourceManager.GetString("_mainAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected:.
        /// </summary>
        public static string _mainConnection {
            get {
                return ResourceManager.GetString("_mainConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string _mainEdit {
            get {
                return ResourceManager.GetString("_mainEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit.
        /// </summary>
        public static string _mainEditAddUnit {
            get {
                return ResourceManager.GetString("_mainEditAddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit installer.
        /// </summary>
        public static string _mainExitApp {
            get {
                return ResourceManager.GetString("_mainExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string _mainFile {
            get {
                return ResourceManager.GetString("_mainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close c_urrent project.
        /// </summary>
        public static string _mainFileClose {
            get {
                return ResourceManager.GetString("_mainFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _system.
        /// </summary>
        public static string _mainFileNewSystem {
            get {
                return ResourceManager.GetString("_mainFileNewSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open file.
        /// </summary>
        public static string _mainFileOpenFile {
            get {
                return ResourceManager.GetString("_mainFileOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save file.
        /// </summary>
        public static string _mainFileSaveFile {
            get {
                return ResourceManager.GetString("_mainFileSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string _mainHelp {
            get {
                return ResourceManager.GetString("_mainHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string _mainHelpAbout {
            get {
                return ResourceManager.GetString("_mainHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User _Manual.
        /// </summary>
        public static string _mainHelpUserManual {
            get {
                return ResourceManager.GetString("_mainHelpUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {0}.
        /// </summary>
        public static string _mainInput {
            get {
                return ResourceManager.GetString("_mainInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string _mainMaster {
            get {
                return ResourceManager.GetString("_mainMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_onnection Settings.
        /// </summary>
        public static string _MainMenuconnection {
            get {
                return ResourceManager.GetString("_MainMenuconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Receive from unit.
        /// </summary>
        public static string _MainMenuReceiveFromUnit {
            get {
                return ResourceManager.GetString("_MainMenuReceiveFromUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to _unit.
        /// </summary>
        public static string _MainMenuSendToUnit {
            get {
                return ResourceManager.GetString("_MainMenuSendToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone 1.
        /// </summary>
        public static string _mainMic1 {
            get {
                return ResourceManager.GetString("_mainMic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone 2.
        /// </summary>
        public static string _mainMic2 {
            get {
                return ResourceManager.GetString("_mainMic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string _mainMonitoring {
            get {
                return ResourceManager.GetString("_mainMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_mail settings.
        /// </summary>
        public static string _mainMonitoringEmailSettings {
            get {
                return ResourceManager.GetString("_mainMonitoringEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string _mainMonitoringMonitoring {
            get {
                return ResourceManager.GetString("_mainMonitoringMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this card?.
        /// </summary>
        public static string _mainMSGDelCardConfirmation {
            get {
                return ResourceManager.GetString("_mainMSGDelCardConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete card.
        /// </summary>
        public static string _mainMSGDelCardTitle {
            get {
                return ResourceManager.GetString("_mainMSGDelCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this slave unit?.
        /// </summary>
        public static string _mainMSGDelUnitConfirmation {
            get {
                return ResourceManager.GetString("_mainMSGDelUnitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete slave unit.
        /// </summary>
        public static string _mainMSGDelUnitTitle {
            get {
                return ResourceManager.GetString("_mainMSGDelUnitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove 4x4 zone card.
        /// </summary>
        public static string _mainRemoveCard {
            get {
                return ResourceManager.GetString("_mainRemoveCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave {0}.
        /// </summary>
        public static string _mainSlave {
            get {
                return ResourceManager.GetString("_mainSlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string _mainTools {
            get {
                return ResourceManager.GetString("_mainTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy save mode.
        /// </summary>
        public static string _mainTools230Fail {
            get {
                return ResourceManager.GetString("_mainTools230Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run calibration complete system.
        /// </summary>
        public static string _mainToolsCalibrationTotal {
            get {
                return ResourceManager.GetString("_mainToolsCalibrationTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Setup connection.
        /// </summary>
        public static string _mainToolsOpenConnectionView {
            get {
                return ResourceManager.GetString("_mainToolsOpenConnectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error _Log.
        /// </summary>
        public static string _mainToolsOpenErrorLog {
            get {
                return ResourceManager.GetString("_mainToolsOpenErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pilot tone.
        /// </summary>
        public static string _mainToolsOpenPilotToneView {
            get {
                return ResourceManager.GetString("_mainToolsOpenPilotToneView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Output contact.
        /// </summary>
        public static string _mainToolsOutputContact {
            get {
                return ResourceManager.GetString("_mainToolsOutputContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redundancy.
        /// </summary>
        public static string _mainToolsRedundancy {
            get {
                return ResourceManager.GetString("_mainToolsRedundancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency panel settings &amp; Routing Matrix.
        /// </summary>
        public static string _mainToolsZoneMatrix {
            get {
                return ResourceManager.GetString("_mainToolsZoneMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string _mainView {
            get {
                return ResourceManager.GetString("_mainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all _windows.
        /// </summary>
        public static string _mainViewCloseWindows {
            get {
                return ResourceManager.GetString("_mainViewCloseWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXentro ECU Installer.
        /// </summary>
        public static string _mainWindowTitle {
            get {
                return ResourceManager.GetString("_mainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa_ve as.
        /// </summary>
        public static string _SaveAs {
            get {
                return ResourceManager.GetString("_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXentro ECU controller software.
        /// </summary>
        public static string AboutwindowText {
            get {
                return ResourceManager.GetString("AboutwindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new unit.
        /// </summary>
        public static string AddUnit {
            get {
                return ResourceManager.GetString("AddUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Amp.
        /// </summary>
        public static string BackupAmpBlock {
            get {
                return ResourceManager.GetString("BackupAmpBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Amp.
        /// </summary>
        public static string BackupAmpTitle {
            get {
                return ResourceManager.GetString("BackupAmpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary {0}.
        /// </summary>
        public static string BlAuxiliary {
            get {
                return ResourceManager.GetString("BlAuxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Amp {0}.
        /// </summary>
        public static string BlBackupAmp {
            get {
                return ResourceManager.GetString("BlBackupAmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup {0}.
        /// </summary>
        public static string BlBkp {
            get {
                return ResourceManager.GetString("BlBkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor.
        /// </summary>
        public static string BlCompr {
            get {
                return ResourceManager.GetString("BlCompr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compr..
        /// </summary>
        public static string BlCompressor {
            get {
                return ResourceManager.GetString("BlCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string BlDelay {
            get {
                return ResourceManager.GetString("BlDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {0}.
        /// </summary>
        public static string BlInputName {
            get {
                return ResourceManager.GetString("BlInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string BlMonitor {
            get {
                return ResourceManager.GetString("BlMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor.
        /// </summary>
        public static string BlockTitleCompressor {
            get {
                return ResourceManager.GetString("BlockTitleCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string BlockTitleDelay {
            get {
                return ResourceManager.GetString("BlockTitleDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEQ.
        /// </summary>
        public static string BlockTitleInputPeq {
            get {
                return ResourceManager.GetString("BlockTitleInputPeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker &amp; Room PEQ.
        /// </summary>
        public static string BlockTitleSpeakerPeq {
            get {
                return ResourceManager.GetString("BlockTitleSpeakerPeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output {0}.
        /// </summary>
        public static string BlOutputName {
            get {
                return ResourceManager.GetString("BlOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass &amp; Treble.
        /// </summary>
        public static string BlTcontrl {
            get {
                return ResourceManager.GetString("BlTcontrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished .
        /// </summary>
        public static string btnFinished {
            get {
                return ResourceManager.GetString("btnFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication .
        /// </summary>
        public static string CommErrorsCount {
            get {
                return ResourceManager.GetString("CommErrorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string CommunicationTab {
            get {
                return ResourceManager.GetString("CommunicationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to mcu.
        /// </summary>
        public static string ConnectedMcu {
            get {
                return ResourceManager.GetString("ConnectedMcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No design is opened. Would you like to create a new design file?.
        /// </summary>
        public static string CreateNewDesign {
            get {
                return ResourceManager.GetString("CreateNewDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new design?.
        /// </summary>
        public static string CreateNewDesignHeader {
            get {
                return ResourceManager.GetString("CreateNewDesignHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design ver {0}.
        /// </summary>
        public static string DesignVersion {
            get {
                return ResourceManager.GetString("DesignVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following units were disconnected and will now reboot: {0}.
        /// </summary>
        public static string DisconnectedUnits {
            get {
                return ResourceManager.GetString("DisconnectedUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected units.
        /// </summary>
        public static string DisconnectedUnitsTitle {
            get {
                return ResourceManager.GetString("DisconnectedUnitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evac Matrix.
        /// </summary>
        public static string EmergencyInput {
            get {
                return ResourceManager.GetString("EmergencyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Matrix.
        /// </summary>
        public static string EmergencyInputs {
            get {
                return ResourceManager.GetString("EmergencyInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ver {0}.
        /// </summary>
        public static string GuiVersion {
            get {
                return ResourceManager.GetString("GuiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer: {0}.
        /// </summary>
        public static string InstallerVersion {
            get {
                return ResourceManager.GetString("InstallerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install mode by default.
        /// </summary>
        public static string InstallModeByDefault {
            get {
                return ResourceManager.GetString("InstallModeByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Mute during 48Vdc operation: .
        /// </summary>
        public static string IsInDcOperationStatusText {
            get {
                return ResourceManager.GetString("IsInDcOperationStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Matrix.
        /// </summary>
        public static string LinkMatrix {
            get {
                return ResourceManager.GetString("LinkMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker EQ Library.
        /// </summary>
        public static string loudspeakerEQLibrary {
            get {
                return ResourceManager.GetString("loudspeakerEQLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker Matrix {0}.
        /// </summary>
        public static string LoudSpeakerMatrix {
            get {
                return ResourceManager.GetString("LoudSpeakerMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string lowVoltOff {
            get {
                return ResourceManager.GetString("lowVoltOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string lowVoltOn {
            get {
                return ResourceManager.GetString("lowVoltOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to enable playback of music when operating from the battery backup system?.
        /// </summary>
        public static string lowvoltQuestion {
            get {
                return ResourceManager.GetString("lowvoltQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string lowvoltQuestionTitle {
            get {
                return ResourceManager.GetString("lowvoltQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Matrix.
        /// </summary>
        public static string MatrixTab {
            get {
                return ResourceManager.GetString("MatrixTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Battery tool.
        /// </summary>
        public static string MenuItemBatteryCalc {
            get {
                return ResourceManager.GetString("MenuItemBatteryCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement 1khz schedule.
        /// </summary>
        public static string menuMeasureMent1k {
            get {
                return ResourceManager.GetString("menuMeasureMent1k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download the configuration from the ESC units, overwriting the configuration in the current open file?.
        /// </summary>
        public static string MessageBoxDownloadText {
            get {
                return ResourceManager.GetString("MessageBoxDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm download.
        /// </summary>
        public static string MessageBoxDownloadTitle {
            get {
                return ResourceManager.GetString("MessageBoxDownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do; at least one MCU has to have a connection. Establish a connection for one of the opened units first!.
        /// </summary>
        public static string MessageBoxNoConnectionText {
            get {
                return ResourceManager.GetString("MessageBoxNoConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections found.
        /// </summary>
        public static string MessageBoxNoConnectionTitle {
            get {
                return ResourceManager.GetString("MessageBoxNoConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MessageBoxSaveFileHeader {
            get {
                return ResourceManager.GetString("MessageBoxSaveFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not saved: {0}.
        /// </summary>
        public static string MessageBoxSaveFileText {
            get {
                return ResourceManager.GetString("MessageBoxSaveFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the configuration of the Esc with the settings as they are in the installer software?.
        /// </summary>
        public static string MessageBoxUploadText {
            get {
                return ResourceManager.GetString("MessageBoxUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm upload.
        /// </summary>
        public static string MessageBoxUploadTitle {
            get {
                return ResourceManager.GetString("MessageBoxUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New System.
        /// </summary>
        public static string NewSystem {
            get {
                return ResourceManager.GetString("NewSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to mcu.
        /// </summary>
        public static string NotConnectedMcu {
            get {
                return ResourceManager.GetString("NotConnectedMcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string NotInstalledWatts {
            get {
                return ResourceManager.GetString("NotInstalledWatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement settings.
        /// </summary>
        public static string OpenMeasurementSettingsMenuEntry {
            get {
                return ResourceManager.GetString("OpenMeasurementSettingsMenuEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd Card manager.
        /// </summary>
        public static string OpenSdCardMannager {
            get {
                return ResourceManager.GetString("OpenSdCardMannager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the current file.
        /// </summary>
        public static string OverwriteAsk {
            get {
                return ResourceManager.GetString("OverwriteAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close file.
        /// </summary>
        public static string OverwriteAskTitle {
            get {
                return ResourceManager.GetString("OverwriteAskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 Khz.
        /// </summary>
        public static string Pilot19k {
            get {
                return ResourceManager.GetString("Pilot19k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Khz.
        /// </summary>
        public static string Pilot20k {
            get {
                return ResourceManager.GetString("Pilot20k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 Khz.
        /// </summary>
        public static string Pilot21k {
            get {
                return ResourceManager.GetString("Pilot21k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 Khz.
        /// </summary>
        public static string Pilot22k {
            get {
                return ResourceManager.GetString("Pilot22k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ProgressFailed {
            get {
                return ResourceManager.GetString("ProgressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished synchronising.
        /// </summary>
        public static string ProgressFinished {
            get {
                return ResourceManager.GetString("ProgressFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeed.
        /// </summary>
        public static string ProgressFinishedTitle {
            get {
                return ResourceManager.GetString("ProgressFinishedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive From Unit.
        /// </summary>
        public static string ReceiveFromUnit {
            get {
                return ResourceManager.GetString("ReceiveFromUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a location to save the new design file.
        /// </summary>
        public static string SaveNewSystem {
            get {
                return ResourceManager.GetString("SaveNewSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new file.
        /// </summary>
        public static string SaveNewSystemTitle {
            get {
                return ResourceManager.GetString("SaveNewSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to unit.
        /// </summary>
        public static string SendToUnit {
            get {
                return ResourceManager.GetString("SendToUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeakerLibrary Editor.
        /// </summary>
        public static string SpeakerLibraryEditorMenuItem {
            get {
                return ResourceManager.GetString("SpeakerLibraryEditorMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes {0}.
        /// </summary>
        public static string TabCloseTooltip {
            get {
                return ResourceManager.GetString("TabCloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of this unit is of a different .esc file. Would you like to continue downloading? {0} .
        /// </summary>
        public static string TimestampVerifyDownload {
            get {
                return ResourceManager.GetString("TimestampVerifyDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data esc mismatch.
        /// </summary>
        public static string TimestampVerifyTitle {
            get {
                return ResourceManager.GetString("TimestampVerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data of this unit is of a different .esc file. Would you like to continue uploading? {0} .
        /// </summary>
        public static string TimestampVerifyUpload {
            get {
                return ResourceManager.GetString("TimestampVerifyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong during downloading.
        /// </summary>
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown installer version.
        /// </summary>
        public static string UnknownInstallerVersion {
            get {
                return ResourceManager.GetString("UnknownInstallerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while receiving...
        /// </summary>
        public static string WaitWhileReceiving {
            get {
                return ResourceManager.GetString("WaitWhileReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while sending...
        /// </summary>
        public static string WaitWhileSending {
            get {
                return ResourceManager.GetString("WaitWhileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Watt.
        /// </summary>
        public static string WattsSignature {
            get {
                return ResourceManager.GetString("WattsSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Matrix.
        /// </summary>
        public static string ZoneMatrix {
            get {
                return ResourceManager.GetString("ZoneMatrix", resourceCulture);
            }
        }
    }
}
