using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace EscInstaller.ImportSpeakers
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.5466
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks />
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class ParametricEQ
    {
        private ParametricEQProperty[] propertyField;

        private string typeNumberField;

        /// <remarks />
        [XmlElement("Property", Form = XmlSchemaForm.Unqualified)]
        public ParametricEQProperty[] Property
        {
            get { return propertyField; }
            set { propertyField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string typeNumber
        {
            get { return typeNumberField; }
            set { typeNumberField = value; }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "2.0.50727.3038")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    public class ParametricEQProperty
    {
        private string nameField;

        private string valueField;

        /// <remarks />
        [XmlAttribute]
        public string name
        {
            get { return nameField; }
            set { nameField = value; }
        }

        /// <remarks />
        [XmlAttribute]
        public string value
        {
            get { return valueField; }
            set { valueField = value; }
        }
    }
}