//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Auxiliary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auxiliary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.Auxiliary", typeof(Auxiliary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        public static string _auxBlockTitle {
            get {
                return ResourceManager.GetString("_auxBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string _auxCh14 {
            get {
                return ResourceManager.GetString("_auxCh14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel link selection.
        /// </summary>
        public static string _auxChLink {
            get {
                return ResourceManager.GetString("_auxChLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ Curve.
        /// </summary>
        public static string _auxGroupEQCurve {
            get {
                return ResourceManager.GetString("_auxGroupEQCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select loudspeaker EQ.
        /// </summary>
        public static string _auxGroupSelectLoudspeaker {
            get {
                return ResourceManager.GetString("_auxGroupSelectLoudspeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker library master.
        /// </summary>
        public static string _auxSpeakerlibrary {
            get {
                return ResourceManager.GetString("_auxSpeakerlibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to:.
        /// </summary>
        public static string _linkChannel {
            get {
                return ResourceManager.GetString("_linkChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ Library.
        /// </summary>
        public static string _speakerLibrary {
            get {
                return ResourceManager.GetString("_speakerLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output level.
        /// </summary>
        public static string AuxGainSlider {
            get {
                return ResourceManager.GetString("AuxGainSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametric EQ.
        /// </summary>
        public static string EqualizerHeader {
            get {
                return ResourceManager.GetString("EqualizerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequence Response.
        /// </summary>
        public static string LibraryEqStages {
            get {
                return ResourceManager.GetString("LibraryEqStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ preset list {0}.
        /// </summary>
        public static string PeqHeader {
            get {
                return ResourceManager.GetString("PeqHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary gain.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary channel {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
