//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Delay {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Delay() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.Delay", typeof(Delay).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string _delayBlockTitle {
            get {
                return ResourceManager.GetString("_delayBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double delay time.
        /// </summary>
        public static string _delayDoubleTime {
            get {
                return ResourceManager.GetString("_delayDoubleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses channel 3 delay block.
        /// </summary>
        public static string _delayDoubletxt {
            get {
                return ResourceManager.GetString("_delayDoubletxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string _delayFeet {
            get {
                return ResourceManager.GetString("_delayFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay parameters.
        /// </summary>
        public static string _delayGroupTitle {
            get {
                return ResourceManager.GetString("_delayGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string _delayMeters {
            get {
                return ResourceManager.GetString("_delayMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string _delayMs {
            get {
                return ResourceManager.GetString("_delayMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add delay of channel 3 to channel 2.
        /// </summary>
        public static string ChainDelayTo2and3 {
            get {
                return ResourceManager.GetString("ChainDelayTo2and3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel 2.
        /// </summary>
        public static string DelayCh2Header {
            get {
                return ResourceManager.GetString("DelayCh2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel 3.
        /// </summary>
        public static string DelayCh3Header {
            get {
                return ResourceManager.GetString("DelayCh3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay max. 60ms. When delay time up to 120ms is used, delay of ch.3 will be added to Ch.2.
        /// </summary>
        public static string DelayNotification {
            get {
                return ResourceManager.GetString("DelayNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay max. 60ms. per channel.
        /// </summary>
        public static string DelayNotificationDelay3 {
            get {
                return ResourceManager.GetString("DelayNotificationDelay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
