//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExternalInput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExternalInput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.ExternalInput", typeof(ExternalInput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Audio input.
        /// </summary>
        public static string _matrixAnnouncExtAudioIn {
            get {
                return ResourceManager.GetString("_matrixAnnouncExtAudioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Panel.
        /// </summary>
        public static string _matrixAnnouncMicEP {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Detection System interface .
        /// </summary>
        public static string _matrixAnnouncMicFDS {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Panel.
        /// </summary>
        public static string _matrixAnnouncMicFP {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 1.
        /// </summary>
        public static string _matrixSelectAlarm {
            get {
                return ResourceManager.GetString("_matrixSelectAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 2.
        /// </summary>
        public static string _matrixSelectAlert {
            get {
                return ResourceManager.GetString("_matrixSelectAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm1 &amp; Alarm2.
        /// </summary>
        public static string AlarmAlertHeader {
            get {
                return ResourceManager.GetString("AlarmAlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm messages.
        /// </summary>
        public static string AlarmMessages {
            get {
                return ResourceManager.GetString("AlarmMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above levels are for connected panels to this ESC unit only and will be forwarded to &apos;below&apos; slave units! 
        ///    No need to set these levels on a Slave ESC if it has no local panels connected!.
        /// </summary>
        public static string ExternalInputFooter {
            get {
                return ResourceManager.GetString("ExternalInputFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-anouncement.
        /// </summary>
        public static string matrixGroupAnnouncements {
            get {
                return ResourceManager.GetString("matrixGroupAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency signal levels.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
