//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InputName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.InputName", typeof(InputName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate VU meter.
        /// </summary>
        public static string _inputAtcivateVU {
            get {
                return ResourceManager.GetString("_inputAtcivateVU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelloEN.
        /// </summary>
        public static string _inputCheckCopyName {
            get {
                return ResourceManager.GetString("_inputCheckCopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy name to output.
        /// </summary>
        public static string _inputCopyToOutput {
            get {
                return ResourceManager.GetString("_inputCopyToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string _inputEnterName {
            get {
                return ResourceManager.GetString("_inputEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string _inputGroupGain {
            get {
                return ResourceManager.GetString("_inputGroupGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input name.
        /// </summary>
        public static string _inputGroupInputName {
            get {
                return ResourceManager.GetString("_inputGroupInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VU Meter.
        /// </summary>
        public static string _inputGroupMonitoring {
            get {
                return ResourceManager.GetString("_inputGroupMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Max. 13 characters).
        /// </summary>
        public static string _inputMax13Chr {
            get {
                return ResourceManager.GetString("_inputMax13Chr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Level.
        /// </summary>
        public static string _InputNameAuxSlider {
            get {
                return ResourceManager.GetString("_InputNameAuxSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route signal to AUX1.
        /// </summary>
        public static string _inputRouteSignal {
            get {
                return ResourceManager.GetString("_inputRouteSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Alert Track.
        /// </summary>
        public static string _StartAlertTrack {
            get {
                return ResourceManager.GetString("_StartAlertTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 1.
        /// </summary>
        public static string BlockAlarm1 {
            get {
                return ResourceManager.GetString("BlockAlarm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 2.
        /// </summary>
        public static string BlockAlarm2 {
            get {
                return ResourceManager.GetString("BlockAlarm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Input.
        /// </summary>
        public static string BlockAux {
            get {
                return ResourceManager.GetString("BlockAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {0} .
        /// </summary>
        public static string BlockInput {
            get {
                return ResourceManager.GetString("BlockInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Bus 1.
        /// </summary>
        public static string BlockMic1 {
            get {
                return ResourceManager.GetString("BlockMic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Bus 2.
        /// </summary>
        public static string BlockMic2 {
            get {
                return ResourceManager.GetString("BlockMic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input gain.
        /// </summary>
        public static string InputGain {
            get {
                return ResourceManager.GetString("InputGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input gain correction.
        /// </summary>
        public static string Sens {
            get {
                return ResourceManager.GetString("Sens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input {0} .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm {0}.
        /// </summary>
        public static string TitleAlarm {
            get {
                return ResourceManager.GetString("TitleAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Input {0}.
        /// </summary>
        public static string TitleAux {
            get {
                return ResourceManager.GetString("TitleAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous {0}.
        /// </summary>
        public static string TitleInput {
            get {
                return ResourceManager.GetString("TitleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Microphone input {0}.
        /// </summary>
        public static string TitleMic {
            get {
                return ResourceManager.GetString("TitleMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vu meter.
        /// </summary>
        public static string VuMeter {
            get {
                return ResourceManager.GetString("VuMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sense input level.
        /// </summary>
        public static string VuMeterSettings {
            get {
                return ResourceManager.GetString("VuMeterSettings", resourceCulture);
            }
        }
    }
}
