//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IntervalSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IntervalSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.IntervalSettings", typeof(IntervalSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 220v setting.
        /// </summary>
        public static string Error220Header {
            get {
                return ResourceManager.GetString("Error220Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval 220v.
        /// </summary>
        public static string Error220VInterval {
            get {
                return ResourceManager.GetString("Error220VInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 48v setting.
        /// </summary>
        public static string Error48Header {
            get {
                return ResourceManager.GetString("Error48Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count 220v.
        /// </summary>
        public static string ErrorValueAmount220 {
            get {
                return ResourceManager.GetString("ErrorValueAmount220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count 48v.
        /// </summary>
        public static string ErrorValueAmount48 {
            get {
                return ResourceManager.GetString("ErrorValueAmount48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval 48v.
        /// </summary>
        public static string InterValueInterval48 {
            get {
                return ResourceManager.GetString("InterValueInterval48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send these settings.
        /// </summary>
        public static string SendParametersButton {
            get {
                return ResourceManager.GetString("SendParametersButton", resourceCulture);
            }
        }
    }
}
