//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Link {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Link() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.Link", typeof(Link).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Matrix.
        /// </summary>
        public static string _linkBlockTitle {
            get {
                return ResourceManager.GetString("_linkBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link selection.
        /// </summary>
        public static string _linkGroup {
            get {
                return ResourceManager.GetString("_linkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No link.
        /// </summary>
        public static string _linkNoLink {
            get {
                return ResourceManager.GetString("_linkNoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to previous channel.
        /// </summary>
        public static string _linkPrev {
            get {
                return ResourceManager.GetString("_linkPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to previous channel after delay.
        /// </summary>
        public static string _linkPrevDelay {
            get {
                return ResourceManager.GetString("_linkPrevDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aux {0}.
        /// </summary>
        public static string AuxLinkBlock {
            get {
                return ResourceManager.GetString("AuxLinkBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel number.
        /// </summary>
        public static string Channum {
            get {
                return ResourceManager.GetString("Channum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Link {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
