//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Monitoring {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Monitoring() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.Monitoring", typeof(Monitoring).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring settings.
        /// </summary>
        public static string _LowImpedanceMonitoring {
            get {
                return ResourceManager.GetString("_LowImpedanceMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string _monitorBlockTitle {
            get {
                return ResourceManager.GetString("_monitorBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate output.
        /// </summary>
        public static string _monitorCalibrateZone {
            get {
                return ResourceManager.GetString("_monitorCalibrateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation (W).
        /// </summary>
        public static string _monitorDeviation1 {
            get {
                return ResourceManager.GetString("_monitorDeviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line A.
        /// </summary>
        public static string _monitorLoadA1 {
            get {
                return ResourceManager.GetString("_monitorLoadA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line A+B.
        /// </summary>
        public static string _monitorLoadAB {
            get {
                return ResourceManager.GetString("_monitorLoadAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line B.
        /// </summary>
        public static string _monitorLoadB1 {
            get {
                return ResourceManager.GetString("_monitorLoadB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string _monitorPlay {
            get {
                return ResourceManager.GetString("_monitorPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string _monitorStop {
            get {
                return ResourceManager.GetString("_monitorStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear calibrated line.
        /// </summary>
        public static string ClearCalibrateOption {
            get {
                return ResourceManager.GetString("ClearCalibrateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indicated deviation values in &apos;Watt&apos; are 5%, 10%, 20%, 30% or 50% of the calibrated load, with a minimum of 10W..
        /// </summary>
        public static string DeviationInfo {
            get {
                return ResourceManager.GetString("DeviationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation Info.
        /// </summary>
        public static string DeviationInfoTitle {
            get {
                return ResourceManager.GetString("DeviationInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 kHz measurement.
        /// </summary>
        public static string Enable1khzMeasure {
            get {
                return ResourceManager.GetString("Enable1khzMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 kHz.
        /// </summary>
        public static string FrequencyLow {
            get {
                return ResourceManager.GetString("FrequencyLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate output.
        /// </summary>
        public static string GbCalibrate {
            get {
                return ResourceManager.GetString("GbCalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure current load.
        /// </summary>
        public static string GbCalibrationOptions {
            get {
                return ResourceManager.GetString("GbCalibrationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring frequency.
        /// </summary>
        public static string GbPilot {
            get {
                return ResourceManager.GetString("GbPilot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play test message.
        /// </summary>
        public static string GbPlayTestMessage {
            get {
                return ResourceManager.GetString("GbPlayTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 kHz.
        /// </summary>
        public static string Khz18 {
            get {
                return ResourceManager.GetString("Khz18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19 kHz.
        /// </summary>
        public static string Khz19 {
            get {
                return ResourceManager.GetString("Khz19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 kHz.
        /// </summary>
        public static string Khz20 {
            get {
                return ResourceManager.GetString("Khz20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 kHz.
        /// </summary>
        public static string Khz21 {
            get {
                return ResourceManager.GetString("Khz21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22 kHz.
        /// </summary>
        public static string Khz22 {
            get {
                return ResourceManager.GetString("Khz22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100V loudspeaker line.
        /// </summary>
        public static string Line100VOption {
            get {
                return ResourceManager.GetString("Line100VOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Impedance line.
        /// </summary>
        public static string LowImpedanceOption {
            get {
                return ResourceManager.GetString("LowImpedanceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate zone.
        /// </summary>
        public static string mboxcalibrateZone {
            get {
                return ResourceManager.GetString("mboxcalibrateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibrate.
        /// </summary>
        public static string mboxcalibrateZoneTitle {
            get {
                return ResourceManager.GetString("mboxcalibrateZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Load.
        /// </summary>
        public static string Measure1k {
            get {
                return ResourceManager.GetString("Measure1k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured load (Ω).
        /// </summary>
        public static string MeasuredOhm {
            get {
                return ResourceManager.GetString("MeasuredOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured load (W).
        /// </summary>
        public static string MeasuredWatt {
            get {
                return ResourceManager.GetString("MeasuredWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line deviation.
        /// </summary>
        public static string MonitoringDeviation1 {
            get {
                return ResourceManager.GetString("MonitoringDeviation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring options.
        /// </summary>
        public static string MonitoringOptions {
            get {
                return ResourceManager.GetString("MonitoringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored load (Ω).
        /// </summary>
        public static string StoredOhm {
            get {
                return ResourceManager.GetString("StoredOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored load (W).
        /// </summary>
        public static string StoredWatt {
            get {
                return ResourceManager.GetString("StoredWatt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output in test mode.
        /// </summary>
        public static string TestModeEnable {
            get {
                return ResourceManager.GetString("TestModeEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
