//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageGain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageGain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.PageGain", typeof(PageGain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output {0} .
        /// </summary>
        public static string _outputBlockTitle {
            get {
                return ResourceManager.GetString("_outputBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string _outputEnterName {
            get {
                return ResourceManager.GetString("_outputEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output name.
        /// </summary>
        public static string _outputGroupName {
            get {
                return ResourceManager.GetString("_outputGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency page and output gain.
        /// </summary>
        public static string _outputGroupPageOutputGain {
            get {
                return ResourceManager.GetString("_outputGroupPageOutputGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Max 13 characters).
        /// </summary>
        public static string _outputMax13Characters {
            get {
                return ResourceManager.GetString("_outputMax13Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string _outputSliderOutput {
            get {
                return ResourceManager.GetString("_outputSliderOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string _outputSliderPage {
            get {
                return ResourceManager.GetString("_outputSliderPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (enables channel).
        /// </summary>
        public static string AmplCheckNotify {
            get {
                return ResourceManager.GetString("AmplCheckNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplifier attached.
        /// </summary>
        public static string IsAmplifierAttached {
            get {
                return ResourceManager.GetString("IsAmplifierAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output gain.
        /// </summary>
        public static string OutputGain {
            get {
                return ResourceManager.GetString("OutputGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page gain.
        /// </summary>
        public static string PageGainSlider {
            get {
                return ResourceManager.GetString("PageGainSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
