//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Panel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Panel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.Panel", typeof(Panel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select: &apos;Keypad (P1-16)&apos; or &apos;ABCD buttons&apos; or &apos;GPO Relay Card&apos;.
        /// </summary>
        public static string _ButtonRangeHeader {
            get {
                return ResourceManager.GetString("_ButtonRangeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Audio input.
        /// </summary>
        public static string _matrixAnnouncExtAudioIn {
            get {
                return ResourceManager.GetString("_matrixAnnouncExtAudioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Panel.
        /// </summary>
        public static string _matrixAnnouncMicEP {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Detection System interface .
        /// </summary>
        public static string _matrixAnnouncMicFDS {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Panel.
        /// </summary>
        public static string _matrixAnnouncMicFP {
            get {
                return ResourceManager.GetString("_matrixAnnouncMicFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button A.
        /// </summary>
        public static string _matrixButtonA {
            get {
                return ResourceManager.GetString("_matrixButtonA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1.
        /// </summary>
        public static string _matrixButtonAlarm {
            get {
                return ResourceManager.GetString("_matrixButtonAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm &amp; Alert.
        /// </summary>
        public static string _matrixButtonAlarmAlertHeader {
            get {
                return ResourceManager.GetString("_matrixButtonAlarmAlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 2.
        /// </summary>
        public static string _matrixButtonAlert {
            get {
                return ResourceManager.GetString("_matrixButtonAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button B.
        /// </summary>
        public static string _matrixButtonB {
            get {
                return ResourceManager.GetString("_matrixButtonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button C.
        /// </summary>
        public static string _matrixButtonC {
            get {
                return ResourceManager.GetString("_matrixButtonC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button D.
        /// </summary>
        public static string _matrixButtonD {
            get {
                return ResourceManager.GetString("_matrixButtonD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPO Card Contacts.
        /// </summary>
        public static string _matrixButtonFDS {
            get {
                return ResourceManager.GetString("_matrixButtonFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD Buttons.
        /// </summary>
        public static string _matrixButtonPanelAD {
            get {
                return ResourceManager.GetString("_matrixButtonPanelAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix selection.
        /// </summary>
        public static string _matrixComboMatrixSelection {
            get {
                return ResourceManager.GetString("_matrixComboMatrixSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message {0}.
        /// </summary>
        public static string _matrixComboMessage {
            get {
                return ResourceManager.GetString("_matrixComboMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string _matrixDisplayValue {
            get {
                return ResourceManager.GetString("_matrixDisplayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alam 1 &amp; Alarm 2.
        /// </summary>
        public static string _matrixGroupAlarmAlert {
            get {
                return ResourceManager.GetString("_matrixGroupAlarmAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-announcements.
        /// </summary>
        public static string _matrixGroupAnnouncements {
            get {
                return ResourceManager.GetString("_matrixGroupAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Panel.
        /// </summary>
        public static string _matrixGroupEvac {
            get {
                return ResourceManager.GetString("_matrixGroupEvac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Detection System.
        /// </summary>
        public static string _matrixGroupFDS {
            get {
                return ResourceManager.GetString("_matrixGroupFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Panel.
        /// </summary>
        public static string _matrixGroupFire {
            get {
                return ResourceManager.GetString("_matrixGroupFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD button setup &amp; Message selection.
        /// </summary>
        public static string _matrixGroupMessage {
            get {
                return ResourceManager.GetString("_matrixGroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Matrix for Keypad buttons / ABCD buttons / GPO Relay Card.
        /// </summary>
        public static string _matrixGroupZoneSelection {
            get {
                return ResourceManager.GetString("_matrixGroupZoneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select eXentro unit to display outputs.
        /// </summary>
        public static string _matrixScrollSelSystemZone {
            get {
                return ResourceManager.GetString("_matrixScrollSelSystemZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 1.
        /// </summary>
        public static string _matrixSelectAlarm {
            get {
                return ResourceManager.GetString("_matrixSelectAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 2.
        /// </summary>
        public static string _matrixSelectAlert {
            get {
                return ResourceManager.GetString("_matrixSelectAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation Panel.
        /// </summary>
        public static string _matrixSelectionEP {
            get {
                return ResourceManager.GetString("_matrixSelectionEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDS Interface.
        /// </summary>
        public static string _matrixSelectionFDS {
            get {
                return ResourceManager.GetString("_matrixSelectionFDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contacts of 1 GPO Card can only be linked to 1 ESC unit! .
        /// </summary>
        public static string _matrixSelectionFDSContacts {
            get {
                return ResourceManager.GetString("_matrixSelectionFDSContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Panel.
        /// </summary>
        public static string _matrixSelectionFP {
            get {
                return ResourceManager.GetString("_matrixSelectionFP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Keypad button.
        /// </summary>
        public static string _matrixSelectionSelectButton {
            get {
                return ResourceManager.GetString("_matrixSelectionSelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone {0}.
        /// </summary>
        public static string _matrixZone {
            get {
                return ResourceManager.GetString("_matrixZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 1 &amp; 2 and Pre-announcement selection.
        /// </summary>
        public static string _PreannAndAlarmAlart {
            get {
                return ResourceManager.GetString("_PreannAndAlarmAlart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCD Button setup: select &apos;Matrix&apos; to activate Routing Matrix.
        /// </summary>
        public static string ABCDButtonsHeader {
            get {
                return ResourceManager.GetString("ABCDButtonsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPO relay is activated when an Alarm message is routed to the selected output:.
        /// </summary>
        public static string AlamAlertMic {
            get {
                return ResourceManager.GetString("AlamAlertMic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm message 1 &amp; 2.
        /// </summary>
        public static string AlarmAlertHeader {
            get {
                return ResourceManager.GetString("AlarmAlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Alarm 1.
        /// </summary>
        public static string AllAlarm {
            get {
                return ResourceManager.GetString("AllAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Alarm 2.
        /// </summary>
        public static string AllAlert {
            get {
                return ResourceManager.GetString("AllAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableFlat.
        /// </summary>
        public static string DisableFlat {
            get {
                return ResourceManager.GetString("DisableFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string FirstABCD {
            get {
                return ResourceManager.GetString("FirstABCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Message.
        /// </summary>
        public static string FirstPreannounce {
            get {
                return ResourceManager.GetString("FirstPreannounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreive messages from system.
        /// </summary>
        public static string MatrixMessagesRetreive {
            get {
                return ResourceManager.GetString("MatrixMessagesRetreive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string MatrixResetMessages {
            get {
                return ResourceManager.GetString("MatrixResetMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreive Messages.
        /// </summary>
        public static string MatrixRetreiveMessages {
            get {
                return ResourceManager.GetString("MatrixRetreiveMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        public static string MessageNo {
            get {
                return ResourceManager.GetString("MessageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Matrix routing table for each button or select messages which will replace the Alarm/Alert messages used for the zone butons routing matrix..
        /// </summary>
        public static string MessSel {
            get {
                return ResourceManager.GetString("MessSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mic-signal is not forwarded if only an &apos;Alarm 2&apos; message is linked to a routing table of a button.
        /// </summary>
        public static string Microphonerouting {
            get {
                return ResourceManager.GetString("Microphonerouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1.
        /// </summary>
        public static string microutingOpt1 {
            get {
                return ResourceManager.GetString("microutingOpt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1 &amp; 2.
        /// </summary>
        public static string microutingOpt2 {
            get {
                return ResourceManager.GetString("microutingOpt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 1.
        /// </summary>
        public static string PanelMessageA {
            get {
                return ResourceManager.GetString("PanelMessageA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm 2.
        /// </summary>
        public static string PanelMessageB {
            get {
                return ResourceManager.GetString("PanelMessageB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message selection &amp; ABCD Button settings.
        /// </summary>
        public static string RightHeader {
            get {
                return ResourceManager.GetString("RightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency panel buttons &amp; GPO.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
