//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SdMessageCard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SdMessageCard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.SdMessageCard", typeof(SdMessageCard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddPreDefinedToCard {
            get {
                return ResourceManager.GetString("AddPreDefinedToCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Canceld.
        /// </summary>
        public static string Canceld {
            get {
                return ResourceManager.GetString("Canceld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CanceldTitle {
            get {
                return ResourceManager.GetString("CanceldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelWrite {
            get {
                return ResourceManager.GetString("CancelWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd card 1.
        /// </summary>
        public static string CardA {
            get {
                return ResourceManager.GetString("CardA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sd card 2.
        /// </summary>
        public static string CardB {
            get {
                return ResourceManager.GetString("CardB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Filemanager *(or drag &amp; drop to add).
        /// </summary>
        public static string DragDropButton {
            get {
                return ResourceManager.GetString("DragDropButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 16Khz file is allready added and cannot be written twice.
        /// </summary>
        public static string Error16KhzIsAllreadyAdded {
            get {
                return ResourceManager.GetString("Error16KhzIsAllreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s only space for 254 tracks.
        /// </summary>
        public static string ErrorAddFileCount {
            get {
                return ResourceManager.GetString("ErrorAddFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file did not contain the necessarily .mp3 extension.
        /// </summary>
        public static string ErrorAddFileMp3Extension {
            get {
                return ResourceManager.GetString("ErrorAddFileMp3Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file.
        /// </summary>
        public static string ErrorAddFileTitle {
            get {
                return ResourceManager.GetString("ErrorAddFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file cannot be played: {0}.
        /// </summary>
        public static string ErrorPlayMessage {
            get {
                return ResourceManager.GetString("ErrorPlayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error playing file.
        /// </summary>
        public static string ErrorPlayTitle {
            get {
                return ResourceManager.GetString("ErrorPlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming file.
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select select at least 7 mandatory messages.
        /// </summary>
        public static string MandatoryWarning {
            get {
                return ResourceManager.GetString("MandatoryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this track.
        /// </summary>
        public static string MoveThisTrack {
            get {
                return ResourceManager.GetString("MoveThisTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing .
        /// </summary>
        public static string NotEnoughMessagesHeader {
            get {
                return ResourceManager.GetString("NotEnoughMessagesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 6 messages have to be written on the card.
        /// </summary>
        public static string NotEnoughMessageText {
            get {
                return ResourceManager.GetString("NotEnoughMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play this track.
        /// </summary>
        public static string PlayTrack {
            get {
                return ResourceManager.GetString("PlayTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message library:.
        /// </summary>
        public static string PredefinedHeader {
            get {
                return ResourceManager.GetString("PredefinedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveMessages {
            get {
                return ResourceManager.GetString("RemoveMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove wrong.
        /// </summary>
        public static string RemoveWrong {
            get {
                return ResourceManager.GetString("RemoveWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ResetDrives {
            get {
                return ResourceManager.GetString("ResetDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write contents to SDcard.
        /// </summary>
        public static string SaveContentToSdCard {
            get {
                return ResourceManager.GetString("SaveContentToSdCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD Card Manager.
        /// </summary>
        public static string SdMessageCardView {
            get {
                return ResourceManager.GetString("SdMessageCardView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message selection:.
        /// </summary>
        public static string SelectedMessages {
            get {
                return ResourceManager.GetString("SelectedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Track.
        /// </summary>
        public static string StopTrack {
            get {
                return ResourceManager.GetString("StopTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No system file is opened, only short filenames will be available in matrix as the cant be linked.
        /// </summary>
        public static string SystemIsNotOpenWarning {
            get {
                return ResourceManager.GetString("SystemIsNotOpenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string TrackLength {
            get {
                return ResourceManager.GetString("TrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TrackLocation {
            get {
                return ResourceManager.GetString("TrackLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0} already exists and is discarded.
        /// </summary>
        public static string TrackNameExists {
            get {
                return ResourceManager.GetString("TrackNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing track.
        /// </summary>
        public static string TrackNameExistsTitle {
            get {
                return ResourceManager.GetString("TrackNameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Trackno {
            get {
                return ResourceManager.GetString("Trackno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File have been written to SDCard.
        /// </summary>
        public static string WriteCompleted {
            get {
                return ResourceManager.GetString("WriteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string WriteCompletedTitle {
            get {
                return ResourceManager.GetString("WriteCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write SD.
        /// </summary>
        public static string WriteToSdCard {
            get {
                return ResourceManager.GetString("WriteToSdCard", resourceCulture);
            }
        }
    }
}
