//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscInstaller.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpeakerLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeakerLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EscInstaller.View.SpeakerLibrary", typeof(SpeakerLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSP &amp; Room PEQ.
        /// </summary>
        public static string _lspBlockTitle {
            get {
                return ResourceManager.GetString("_lspBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ Curve.
        /// </summary>
        public static string _lspCurveGroupTitle {
            get {
                return ResourceManager.GetString("_lspCurveGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select loudspeaker EQ.
        /// </summary>
        public static string _lspSelectEQ {
            get {
                return ResourceManager.GetString("_lspSelectEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker library master.
        /// </summary>
        public static string _lspSpeakerLibrary {
            get {
                return ResourceManager.GetString("_lspSpeakerLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string _lspSpeakerListDescription {
            get {
                return ResourceManager.GetString("_lspSpeakerListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string _lspSpeakerListName {
            get {
                return ResourceManager.GetString("_lspSpeakerListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string _lspSpeakerListVersion {
            get {
                return ResourceManager.GetString("_lspSpeakerListVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker &amp; Room EQ.
        /// </summary>
        public static string _lspWindowTitle {
            get {
                return ResourceManager.GetString("_lspWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        public static string _micPEQBand {
            get {
                return ResourceManager.GetString("_micPEQBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEQ.
        /// </summary>
        public static string _micPEQBlockTitle {
            get {
                return ResourceManager.GetString("_micPEQBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost.
        /// </summary>
        public static string _micPEQBoost {
            get {
                return ResourceManager.GetString("_micPEQBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string _micPEQEnable {
            get {
                return ResourceManager.GetString("_micPEQEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string _micPEQFreq {
            get {
                return ResourceManager.GetString("_micPEQFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ Curve.
        /// </summary>
        public static string _micPEQGroupEQCurve {
            get {
                return ResourceManager.GetString("_micPEQGroupEQCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string _micPEQOrder {
            get {
                return ResourceManager.GetString("_micPEQOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string _micPEQQ {
            get {
                return ResourceManager.GetString("_micPEQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string _micPEQType {
            get {
                return ResourceManager.GetString("_micPEQType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ Library.
        /// </summary>
        public static string _speakerLibrary {
            get {
                return ResourceManager.GetString("_speakerLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Speaker into MCU.
        /// </summary>
        public static string _SpeakerLibraryLoadButtonToolTip {
            get {
                return ResourceManager.GetString("_SpeakerLibraryLoadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove speaker from user library.
        /// </summary>
        public static string _SpeakerLibraryRemoveButtonToolTip {
            get {
                return ResourceManager.GetString("_SpeakerLibraryRemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save speaker to user library.
        /// </summary>
        public static string _SpeakerLibrarySaveButtonToolTip {
            get {
                return ResourceManager.GetString("_SpeakerLibrarySaveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new param.
        /// </summary>
        public static string AddNewParam {
            get {
                return ResourceManager.GetString("AddNewParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new speaker.
        /// </summary>
        public static string AddNewSpeaker {
            get {
                return ResourceManager.GetString("AddNewSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import .peq.
        /// </summary>
        public static string ButtonImport {
            get {
                return ResourceManager.GetString("ButtonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By closing this window changes will be lost, are you sure?.
        /// </summary>
        public static string CancelCloseWindowText {
            get {
                return ResourceManager.GetString("CancelCloseWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CancelCloseWindowTitle {
            get {
                return ResourceManager.GetString("CancelCloseWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure removing all biquad settings?.
        /// </summary>
        public static string DeleteAllParamsVerify {
            get {
                return ResourceManager.GetString("DeleteAllParamsVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all params.
        /// </summary>
        public static string DeleteAllParamsVerifyTitle {
            get {
                return ResourceManager.GetString("DeleteAllParamsVerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametric EQ.
        /// </summary>
        public static string EqualizerHeader {
            get {
                return ResourceManager.GetString("EqualizerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string EqualizerRemovePeq {
            get {
                return ResourceManager.GetString("EqualizerRemovePeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EqualizerSavePeq {
            get {
                return ResourceManager.GetString("EqualizerSavePeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat EQ.
        /// </summary>
        public static string FlatEQ {
            get {
                return ResourceManager.GetString("FlatEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get redundancy data.
        /// </summary>
        public static string GetPeqParams {
            get {
                return ResourceManager.GetString("GetPeqParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequence Response.
        /// </summary>
        public static string LibraryEqStages {
            get {
                return ResourceManager.GetString("LibraryEqStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cannot be edited because the same name occurs in the library. Choose a different name.
        /// </summary>
        public static string LockWarning {
            get {
                return ResourceManager.GetString("LockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this speaker up/down.
        /// </summary>
        public static string MoveThisSpeaker {
            get {
                return ResourceManager.GetString("MoveThisSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name exists in library and belongs to a different configuration, please choose a different name.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate name.
        /// </summary>
        public static string NameExistsTitle {
            get {
                return ResourceManager.GetString("NameExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen speaker EQ requires {0} biquads (possibly due to a 4th or higher order filter, requiring 2 biquads).
        ///
        ///This EQ has space for {1} biquads; change EQ parameters and save as a custom EQ in the library then select this new EQ to upload.
        ///    .
        /// </summary>
        public static string NotEnoughSpaceWarning {
            get {
                return ResourceManager.GetString("NotEnoughSpaceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough dsp biquads.
        /// </summary>
        public static string NotEnoughSpaceWarningTitle {
            get {
                return ResourceManager.GetString("NotEnoughSpaceWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQ preset list {0}.
        /// </summary>
        public static string PeqHeader {
            get {
                return ResourceManager.GetString("PeqHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current library selection into selected preset.
        /// </summary>
        public static string PutLibSelection {
            get {
                return ResourceManager.GetString("PutLibSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all parameters.
        /// </summary>
        public static string RemoveAllParams {
            get {
                return ResourceManager.GetString("RemoveAllParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove speaker from library.
        /// </summary>
        public static string RemoveThisSpeaker {
            get {
                return ResourceManager.GetString("RemoveThisSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker Saved Succesfully in library.
        /// </summary>
        public static string SavedSucces {
            get {
                return ResourceManager.GetString("SavedSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedSuccesTitle {
            get {
                return ResourceManager.GetString("SavedSuccesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save library file.
        /// </summary>
        public static string SaveLibFile {
            get {
                return ResourceManager.GetString("SaveLibFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create speaker in library with the same name.
        /// </summary>
        public static string SpeakerExistsMessage {
            get {
                return ResourceManager.GetString("SpeakerExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker allready exists.
        /// </summary>
        public static string SpeakerExistsTitle {
            get {
                return ResourceManager.GetString("SpeakerExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loudspeaker &amp; Room PEQ {0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
